# Simplified and fixed pkgdown workflow
on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
      - name: Build and deploy pkgdown site
        uses: r-lib/actions/pkgdown@v2
        with:
          build_dir: .